version: "2.0.0.{build}"

branches:
  only:
    - master

skip_branch_with_pr: true

max_jobs: 1

image: Visual Studio 2019

dotnet_csproj:
  patch: true
  file: '.\src\**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

platform: Any CPU

configuration: Release

before_build:
  - dotnet restore ./src/LittlePipeline.sln

build:
  project: src\LittlePipeline.sln
  verbosity: normal

after_build:
  - nuget pack artifacts\LittlePipeline.nuspec -Version %APPVEYOR_BUILD_VERSION%

artifacts:
  - path: '*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: EOpeWWE5EpQ9UtHt4PECvi4Gfr1oqMioOm9mM+4FxXBEdvfoIdO6JDFgpRivCckA
  skip_symbols: false
