version: "1.0.0.{build}"

branches:
  only:
    - master

skip_branch_with_pr: true

max_jobs: 1

image: Visual Studio 2017

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU

configuration: Release

before_build:
  - nuget restore src\LittlePipeline.sln

build:
  project: src\LittlePipeline.sln
  verbosity: normal