name: Release to NuGet

on:
  push:
    tags: ['v\d+.\d+.\d+']
    
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/LittlePipeline.sln'
    
    runs-on: ubuntu-latest
    
    timeout-minutes: 5
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: dotnet build $SOLUTION -c $BUILD_CONFIG
    - name: Test
      run: dotnet test $SOLUTION -c $BUILD_CONFIG --no-build
    #- name: Pack
      #run: dotnet pack $SOLUTION -c $BUILD_CONFIG --no-build --output .
    - name: Push
      run: echo '${{ github.ref }}'
      #run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json