name: Release to NuGet

on:
  push:
    tags: ['\d+.\d+.\d+']
    
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/LittlePipeline.sln'
      PROJECT: 'src/LittlePipeline.Std20/LittlePipeline.Std20.csproj'
    
    runs-on: ubuntu-latest
    
    timeout-minutes: 5
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: dotnet build $SOLUTION -c $BUILD_CONFIG /p:Version=${{ github.ref }}
    - name: Test
      run: dotnet test $SOLUTION -c $BUILD_CONFIG --no-build
    - name: Pack
      run: dotnet pack $PROJECT -c $BUILD_CONFIG -o . /p:Version=${{ github.ref }} --no-build
    - name: Push
      #run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json